//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifestyleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class imgdata
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string Proid { get; set; }
        public string Catid { get; set; }
    }
}
