//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifestyleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        public string orderID { get; set; }
        public string Email_id { get; set; }
        public string Proid { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
        public string status_ { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
