//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifestyleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUSer
    {
        public string emailid { get; set; }
        public string Name { get; set; }
        public string pass { get; set; }
        public string usertype { get; set; }
    }
}
